version: '3'
services:
  flask:
    build: .
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./uploaded_files:/app/uploaded_files

networks:
  default:
    external:
      name: dockerInternal

