version: '3'

services:
  api:
    env_file: ".env"
  proxy:
    ports:
      - ${EXPOSE_ON:-8100}:80
    networks:
      - default
      - internet

networks:
  default:
    external:
      name: dockerInternal
  internet:
    driver: bridge
