version: '3'

services:
  web:
    image: edulint/edulint-web-frontend:${FRONTEND_TAG:-latest}
    restart: unless-stopped

  api:
    build: .
    restart: unless-stopped
    volumes:
      - ./codes:/app/codes
      - ./databases:/app/databases
      - ./logs/flask_api:/app/logs
    # todo: sync is needed due to python path changes from different edulint version
    # entrypoint: [ "gunicorn", "--bind", "0.0.0.0:5000", "-w", "4", "--worker-class", "sync", "app:app" ]

  proxy:
    image: nginx:1.23-alpine
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
      - api
    links:
      - web
      - api
