version: '3'

services:
  web:
    image: edulint/edulint-web:latest
    build: .
    restart: unless-stopped
    volumes:
      - ./codes:/app/codes
      - ./logs/flask_web:/app/logs
    entrypoint: [ "gunicorn", "--bind", "0.0.0.0:5000", "-w", "4", "--worker-class", "gevent", "app:app" ]

  api:
    image: edulint/edulint-web:latest
    build: .
    restart: unless-stopped
    volumes:
      - ./codes:/app/codes
      - ./logs/flask_api:/app/logs

  proxy:
    image: nginx:1.23-alpine
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
      - api
    links:
      - web
      - api
