version: '3'

services:
  web:
    build: .
    restart: unless-stopped
    volumes:
      - ./codes:/app/codes
    entrypoint: [ "gunicorn", "--bind", "0.0.0.0:5000", "-w", "4", "--worker-class", "gevent", "app:app" ]

  api:
    build: .
    restart: unless-stopped
    volumes:
      - ./codes:/app/codes
    entrypoint: [ "gunicorn", "--bind", "0.0.0.0:5000", "-w", "4", "--worker-class", "sync", "app:app" ]

  proxy:
    build: ./nginx/
    restart: unless-stopped
    depends_on:
      - web
      - api
    links:
      - web
      - api
