name: Start remote deploy

on:
  push:
    branches:
      main

jobs:
  Start-remote-deploy:
    runs-on: ubuntu-latest
    steps:
      - run: curl https://${{ secrets.DEPLOY_HTTP_AUTH }}@docker_restarter.rechtackova.cz/edulint-web
