name: Start remote deploy
on: [push]
jobs:
  Start-remote-deploy:
    runs-on: ubuntu-latest
    steps:
      - run: curl https://${{ secrets.DEPLOY_HTTP_AUTH }}@docker_restarter.rechtackova.cz/edulint
